### ISSUE TITLE
`copy_to_clipboard()` error

### ISSUE THREAD

**Issue by lf2a** [botcity-dev/botcity-framework-core-python#14]
**Describe the bug**
`copy_to_clipboard()` raises error:

```python
/media/luiz/Dados/repo/android-test/venv/bin/python /media/luiz/Dados/repo/android-test/android.py
Traceback (most recent call last):
  File "/media/luiz/Dados/repo/android-test/android.py", line 72, in <module>
    bot.copy_to_clipboard(text='')
  File "/media/luiz/Dados/repo/android-test/venv/lib/python3.8/site-packages/botcity/core/bot.py", line 845, in copy_to_clipboard
    pyperclip.copy(text)
  File "/media/luiz/Dados/repo/android-test/venv/lib/python3.8/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/media/luiz/Dados/repo/android-test/venv/lib/python3.8/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
```

**Expected behavior**
Copy text to clipboard

**Steps to Reproduce**
```python
from botcity.core import DesktopBot

bot = DesktopBot()
bot.copy_to_clipboard(text='')
print(bot.get_clipboard())
```

**My Platform**
    * OS: Ubuntu 20.04
    * Python Version: 3.8.10
    * Packages Version: `botcity-framework-core=0.2.8`

**Additional context**

**Comment by lf2a** [comment]
Solved!

I had to install: `sudo apt-get install xclip`.

[https://stackoverflow.com/questions/51662213/cant-get-pyperclip-to-use-copy-and-paste-modules-on-python3](https://stackoverflow.com/questions/51662213/cant-get-pyperclip-to-use-copy-and-paste-modules-on-python3)
